# Generated by Django 4.2.1 on 2023-05-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guess_can_pause',
            new_name='guest_can_pause',
        ),
    ]
